version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    ports:
      - "5433:5432"
    env_file:
      - .env

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
      echo 'Starting Django server...';
      exec gunicorn --bind 0.0.0.0:8000 invest_era.wsgi:application --workers 2;
      "
